import express from 'express';
import cors from 'cors';

const app = express();
app.use(cors());
app.use(express.json());

// RxDB replication: pull changes from server
app.post('/pull', (req, res) => {
  const { checkpoint } = req.body as { checkpoint?: string };

  console.log(`[Pull] checkpoint=${checkpoint ?? 'none'}`);

  // Stub: return a realistic annotation document so the frontend
  // can demonstrate replication is working (new doc appears in UI).
  // Each pull returns different data — title/id include current timestamp,
  // position varies slightly so defects don't stack at the same coordinate.
  const now = new Date().toISOString();
  const timestamp = Date.now();
  const spread = 0.001; // ~100m spread around building centre

  res.json({
    documents: [{
      id: `stub-defect-${timestamp}`,
      assetId: 'asset-real-building-01',
      title: `Stub Defect ${now}`,
      description: 'Auto-generated by replication stub — demonstrates sync working',
      severity: ['low', 'medium', 'high', 'critical'][Math.floor(Math.random() * 4)] as 'low' | 'medium' | 'high' | 'critical',
      status: 'open' as const,
      positionXyz: [
        151.2093 + (Math.random() - 0.5) * spread,
        -33.8688 + (Math.random() - 0.5) * spread,
        18 + Math.random() * 5
      ] as [number, number, number],
      templateId: 'tpl-facade-spalling',
      templateValues: {},
      author: 'Replication Stub',
      createdAt: now,
      updatedAt: now
    }],
    checkpoint: now
  });
});

// RxDB replication: push local changes to server
app.post('/push', (req, res) => {
  const { documents } = req.body as { documents?: unknown[] };

  console.log(`[Push] documentCount=${documents?.length ?? 0}`);

  // Stub: accept anything, return success ack
  res.json({
    status: 'success'
  });
});

const PORT = process.env.PORT || 3001;

app.listen(PORT, () => {
  console.log(`[Server] Trendspek replication backend on http://localhost:${PORT}`);
  console.log(`[Server] POST /pull  — RxDB pull changes`);
  console.log(`[Server] POST /push  — RxDB push changes`);
});
